name: Build 🛠️
permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch: # can call manually
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run the tests
    strategy:
      matrix:
         node-version: ['24.x', '26.x']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - run: npm run test

  comment-success-on-pr:
    if: success()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Add Success Comment to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: build
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            Lint, build and test passing for commit ${{ github.event.pull_request.head.sha }} 🚀

  comment-failure-on-pr:
    if: failure()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Add Failure Comment to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: build
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            Lint, build and test FAILING for commit ${{ github.event.pull_request.head.sha }} 💥
